### ISSUE TITLE
Some dependencies are missing with no error/warning 

### ISSUE THREAD

**Issue by dimitrisfasoulas** [codepunkt/webpack-license-plugin#706]
Please have a look at [this repo](https://github.com/dimitrisfasoulas/webpack-license) to reproduce the issue.

In the example above date-fns is imported, it is part of the build but the oss-licenses.json is empty.

I found a few dependencies in some of my projects that are also missing: 

- @popperjs/core (2.4.4)
- deepmerge (2.1.1)
- dom-helpers (5.0.1)
- formik (2.2.9)
- history (4.10.0)
- loadash-es (4.17.11)
- mini-create-react-context (0.4.1)
- react-router (5.2.1)
- react-router-dom (5.2.1)
- react-transition-group (4.4.2)
- resolve-pathname (3.0.0)
- single-spa-react (3.2.0)
- stylis (4.0.3)
- symbol-observable (4.0.0)
- tiny-invariant (1.0.2)
- tiny-warning (1.0.2)
- uuid (3.3.2)
- value-equal (1.0.1)

**Comment by dimitrisfasoulas** [comment]
Upon further investigation, it seems some dependencies are ignored based on webpack mode.
So in the same repo if you run `npm run wp -- --mode='development'` then the oss-licenses.json contains date-fns.

Is this how its supposed to work or is it a bug ?

**Comment by codepunkt** [comment]
webpack with `mode` set to "development" can do other optimizations, depending on the codebase. So it's perfectly reasonable to have certain dependencies in development mode builds that are not included in production mode builds (and in theory, vice versa).

in your simple example, that's not the case though. not sure what happens in "development" builds, this plugin is meant to be used for production builds only. usually, i don't even include it in the configuration for development builds because it would slow down my webpack-dev-server.

**Comment by dimitrisfasoulas** [comment]
Then I guess this should be categorized as a bug since production mode is not reporting the correct list of OSS licenses. This is true for the rest of the libraries I mentioned in the original post. All of those libraries are not listed when the mode is set to production

**Comment by codepunkt** [comment]
After having a look at the repro repo today, it indeed seems like a bug. Will continue to investigate tomorrow.

Thanks for reporting and providing the simple repro!

**Comment by WIStudent** [comment]
I was curious and took a look. The issue seems to be caused by the WebpackModuleFileIterator
```typescript
if (module.dependencies) {
  module.dependencies.forEach(dep => {
    if (dep.originModule && dep.originModule.resource) {
      callback(dep.originModule.resource)
    }
  })
}
```
It seems that in webpack 5 the property `originModule` no longer exists (https://github.com/webpack/webpack/pull/7861). If I use the property `_parentModule` instead the depencency will be correctly recognized.

```typescript
if (module.dependencies) {
  module.dependencies.forEach(dep => {
    if (dep.originModule && dep.originModule.resource) {
      callback(dep.originModule.resource)
    }
    if (dep._parentModule && dep._parentModule.resource) {
      allback(dep._parentModule.resource);
    }
  })
}
```

Using the [Module and Chunk Graph](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#module-and-chunk-graph) to find the dependencies would probably be the cleaner way but this would require dropping support for webpack 2-4.

**Comment by WIStudent** [comment]
Update: I guess every Dependency object hast a `_parentModule` field and the ModuleGraph also simply returns that field:
```js
class Dependency {
	constructor() {
		/** @type {Module} */
		this._parentModule = undefined;
                ....
        }
        ....
}
```
https://github.com/webpack/webpack/blob/5a26b7c4a923c42022ca97fe9cbf46907a20d6d8/lib/Dependency.js#L88-L91

```js
/**
* @param {Dependency} dependency the dependency
* @returns {Module} parent module
*/
getParentModule(dependency) {
    return dependency._parentModule;
}
```
https://github.com/webpack/webpack/blob/5a26b7c4a923c42022ca97fe9cbf46907a20d6d8/lib/ModuleGraph.js#L159-L165

So I think it would be safe to access _parentModule directly.

**Comment by codepunkt** [comment]
> Using the [Module and Chunk Graph](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#module-and-chunk-graph) to find the dependencies would probably be the cleaner way but this would require dropping support for webpack 2-4.

I would be fine doing that. By now, most people should be on webpack v5. That should also simplify the codebase quite a bit.
