### ISSUE TITLE
Output includes licenses of devDependencies

### ISSUE THREAD

**Issue by Semantu** [codepunkt/webpack-license-plugin#737]
This may just be my limited understanding, but my output json file includes licenses for `webpack` amongst other things. I do not depend on webpack directly but a build tool in `devDependencies` depends on webpack. 

Is this expected behaviour? I would have thought licenses of dev dependencies would not need to be included since I'm not re-distributing them in any bundles etc.

**Comment by codepunkt** [comment]
Applications bundled with `webpack` need the [webpack runtime](https://webpack.js.org/concepts/manifest/#runtime) when running. A (small) part of webpack is included in your build output because of that.

Aside from this very specific example, there is no distinction being made between `dependencies` and `devDependencies`. Regardless of the type of dependency, it's possible that it's part of the build output. If it is, this plugin lists it.

If you need further clarification or examples, ask away.
